name: build & deploy

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Use Node 16.x
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Archive build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: deploy_dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v4.1.8
        with:
          name: deploy_dist
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy_dist/blog/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
